// Diagnose why text-field appearances don't render with updateFieldAppearances: false.
import { readFileSync, writeFileSync } from "node:fs";
import { createCanvas, Path2D, ImageData, DOMMatrix } from "@napi-rs/canvas";
import { getDocument } from "pdfjs-dist/legacy/build/pdf.mjs";
import { PDFDocument, PDFName, PDFDict, PDFRef, StandardFonts, PDFString } from "pdf-lib";
import { inflateSync } from "node:zlib";

globalThis.Path2D = Path2D;
globalThis.ImageData = ImageData;
globalThis.DOMMatrix = DOMMatrix;

async function inkAt(file, rect) {
  const doc = await getDocument({
    data: new Uint8Array(readFileSync(new URL(`./${file}`, import.meta.url))),
    useWorkerFetch: false,
    isEvalSupported: false,
    useSystemFonts: true,
  }).promise;
  const page = await doc.getPage(1);
  const viewport = page.getViewport({ scale: 2 });
  const canvas = createCanvas(Math.ceil(viewport.width), Math.ceil(viewport.height));
  const ctx = canvas.getContext("2d");
  await page.render({ canvasContext: ctx, viewport, canvas }).promise;
  const [x1, y1] = viewport.convertToViewportPoint(rect.x, rect.y + rect.h);
  const [x2, y2] = viewport.convertToViewportPoint(rect.x + rect.w, rect.y);
  const img = ctx.getImageData(Math.floor(x1), Math.floor(y1), Math.ceil(x2 - x1), Math.ceil(y2 - y1));
  let dark = 0;
  for (let i = 0; i < img.data.length; i += 4) {
    if (0.299 * img.data[i] + 0.587 * img.data[i + 1] + 0.114 * img.data[i + 2] < 200) dark++;
  }
  return dark;
}

// TF8 = Patient Name field (130.7, 644, 168.7, 11.5)
const TF8 = { x: 130.7, y: 644, w: 168.7, h: 11.5 };

// Build two variants the way the generator does:
async function build(updateAp) {
  const doc = await PDFDocument.load(readFileSync(new URL("./cleaned.pdf", import.meta.url)));
  const form = doc.getForm();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const tf = form.getTextField("Text Field 8");
  tf.defaultUpdateAppearances(font);
  tf.acroField.getWidgets()[0].dict.set(PDFName.of("DA"), PDFString.of("/Helv 9 Tf 0 g"));
  tf.setText("Jane Doe");
  // inspect the appearance generated by setText BEFORE flatten
  const ap = tf.acroField.getWidgets()[0].dict.get(PDFName.of("AP"));
  const apDict = ap ? doc.context.lookup(ap) : undefined;
  const nRef = apDict?.get(PDFName.of("N"));
  const nObj = nRef ? doc.context.lookup(nRef) : undefined;
  console.log(`[before flatten, updateAp=${updateAp}] AP /N target:`, nObj?.constructor?.name);
  if (nObj?.constructor?.name === "PDFRawStream" || nObj?.constructor?.name === "PDFStream") {
    const raw = nObj.getContents();
    let text = "";
    try { text = inflateSync(raw).toString("latin1"); } catch { text = raw.toString("latin1"); }
    console.log("  content:", JSON.stringify(text.slice(0, 200)));
    const resRef = nObj.dict.get(PDFName.of("Resources"));
    console.log("  /Resources:", resRef?.constructor?.name);
    const res = resRef ? doc.context.lookup(resRef) : undefined;
    if (res instanceof PDFDict) {
      const fontRef = res.get(PDFName.of("Font"));
      const fonts = fontRef ? doc.context.lookup(fontRef) : undefined;
      if (fonts instanceof PDFDict) {
        for (const [k, v] of fonts.entries()) {
          const f = v instanceof PDFRef ? doc.context.lookup(v) : v;
          console.log("    font /" + k, "->", f?.constructor?.name, f instanceof PDFDict ? JSON.stringify(f.entries().map(([kk, vv]) => kk.toString() + "=" + vv?.constructor?.name)) : "");
        }
      }
    }
  }
  form.flatten({ updateFieldAppearances: updateAp });
  const out = await doc.save();
  const file = updateAp ? "text-ap-true.pdf" : "text-ap-false.pdf";
  writeFileSync(new URL(`./${file}`, import.meta.url), out);
  return file;
}

console.log("baseline template ink at TF8:", await inkAt("cleaned.pdf", TF8));
const f1 = await build(true);
console.log(`[updateAp=true ] flattened ink at TF8:`, await inkAt(f1, TF8));
const f2 = await build(false);
console.log(`[updateAp=false] flattened ink at TF8:`, await inkAt(f2, TF8));
